// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Listen(arg1) {
  return window['go']['auto']['AutoRecord']['Listen'](arg1);
}

export function OnListen(arg1) {
  return window['go']['auto']['AutoRecord']['OnListen'](arg1);
}

export function Run() {
  return window['go']['auto']['AutoRecord']['Run']();
}
