// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Listen(arg1:any):Promise<void>;

export function OnListen(arg1:boolean):Promise<void>;

export function Run():Promise<void>;
