// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ChangeCurrentTemplate(arg1) {
  return window['go']['template']['Template']['ChangeCurrentTemplate'](arg1);
}

export function CreateTemplate(arg1) {
  return window['go']['template']['Template']['CreateTemplate'](arg1);
}

export function GetAll() {
  return window['go']['template']['Template']['GetAll']();
}
