// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {template} from '../models';

export function GetAll():Promise<Array<template.Template>>;
